### ISSUE TITLE
[Mega-thread] Wiki Updates

### ISSUE THREAD

**Issue by brettgus** [RocketMap/PokeAlarm#185]
**This thread will be used internally to track additions/changes that will potentially be made to the wiki. If you have an issue with something on the wiki, please comment below.**

If you wish to help with updating some aspect of the wiki, you can submit a request to https://github.com/kvangent/PokeAlarmWiki

**TODO:**
- overhaul the wiki for v3

**Comment by brettgus** [comment]
- running server using -H 127.0.0.1 vs -H 0.0.0.0 for internal only/external access
- running multiple pokealarms concurrently in order to have different sets of monitored pokemon
- google maps api key required in which circumstances and which api key features have to be enabled
- telegram: If you want an icon, telegram supports HTML markup. You could put <img>"https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png"</img> in your message body and it should show an image (needs to be tested first)

**Comment by reme-dy** [comment]
- Slack maps
- Geofencing

**Comment by jorgebsa** [comment]
May i suggest a how-to on Docker, given that the dockerfile already exists? Btw, i've been using it since mon/tue and it works like a charm, thanks for the work you all have put into this 👍 

If you want help with it, I could write a simple docker how-to and submit a PR so you can take a look into it! :)

**Comment by kvangent** [comment]
@jorgebsa Feel free to submit any wiki related changes [here](https://github.com/kvangent/PokeAlarmWiki)

**Comment by jorgebsa** [comment]
[Done](https://github.com/kvangent/PokeAlarmWiki/pull/23), waiting for feedback :)

**Comment by kvangent** [comment]
Current Wiki Overhaul Outline:

**Comment by reme-dy** [comment]
Wiki article currently developing:

- v3 quick start guide

Code To Do:

- Remove quotes from "Amer/City" to Amer/City
- Review Discord code (ability to use same alarms.json but notify multiple discord channels)

**Comment by kvangent** [comment]
Issues with the wiki should be submitted via https://github.com/RocketMap/PokeAlarmWiki.
