### ISSUE TITLE
[ENHANCEMENT] Summary List of ongoing raids & unique raid id

### ISSUE THREAD

**Issue by alexccs** [RocketMap/PokeAlarm#421]
## Enhancement Description
Is it possible to add the list of filtered ongoing raids after each notification, or repost every few minutes,

also a unique ID for each posted raid, like (raid uid, pkm, duration, time left) 
However got no idea for ID format yet, need consistence even PA restarted/repost.

## Use cases
1. Easy reading  
2. Less confusion when ppl coordinate groups for specific raid.

example:
Raid on Lugia!  #RLUG133
Available until 14:00  (time left: 01:59 mins). 
google map link

Ongoing Raids:  
#RZAP238 Zapdos 11:00 - 13:00 (time left: 01:00 mins)
google map link
#RMOL222 Moltres 10:30 - 12:30(time left: 30 mins)
google map link

**Comment by kvangent** [comment]
Raids are only 1 per gym and they have time limits, so it doesn't seem very useful to add a new way to identify them. They already have gyms, gym_ids, and locations that are unique.
