### ISSUE TITLE
[BUG] The tag <team_id> used in the gym alarm example doesn't work

### ISSUE THREAD

**Issue by dreamserpent** [RocketMap/PokeAlarm#432]
!--- [BUGUSER SPECIFIC] Use this template if PokeAlarm is behaving in an incorrect or unexpected way.   ---
## Problem Description
when the variable text <team_id> is used in a url, as shown in the gym alarm example, the image is excluded from the alarm. this also happens when <team_id> is used in "avatar_url"

deleting the "icon_url" line results in default behavior which is similar to what oen might expect from the included line

## Your Environment
!--- Please post as many details  --
Operating System : Windows 7 Home 
Python Version (use `python -V`)  : 2.74
RocketMap startup command `cmd`  : python ./runserver.py (no arguments, using config.ini with gym-info and wh-types:[pokemon, gym, raid, egg, tth, gym-info, pokestop, lure] 
PokeAlarm startup command `cmd`: c:\python27\python.exe C:\Users\Chris\PokeAlarm\PokeAlarm\start_pokealarm.py %*

Did the issue persist after restarting the script yesno
yes

## Console Output
!--- Please post any relevant output provided from the PokeAlarm when you ran it --

this is the only gym related console output

```
22017-09-09 23:24:31,812 [     manager_10][   Manager][    INFO] Gym rejected: N
eutral as old team is not correct (F #0)
017-09-09 23:24:31,812 [      manager_3][   Manager][    INFO] Gym rejected: Neu
tral as old team is not correct (F #0)
2017-09-09 23:24:31,812 [      manager_5][   Manager][    INFO] Gym (ZWI3YjA0YjM
0MmJkNDUxZTk0Y2EyNTg0M2E3MTEzNDguMTY=) notification has been triggered!
```

## Your Alarms Config
!--- Please post the config for your alarms in the space below --
!--- Remove all person data such as API_KEYs or CHAT_IDs --
```json
}
"active": "True",
    "type":"discord",
    "webhook_url":"DISCORD_WEBHOOK_URL_FOR_FALLBACK",
    "startup_message":"False",
    "gym":{
      "webhook_url":"DISCORD_WEBHOOK_URL_FOR_GYM_CHANNEL",
      "username":"<geofence>",
      "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/gym_<team_id>.png",
      "title": "<geofence> gym",
      "url": "<gmaps>",
      "body": "is now <new_team>."
    }
)
```

## Troubleshooting Checklist
[X] Most recent version of RocketMap
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

!--- END OF [BUGUSER SPECIFIC] TEMPLATE ---REMOVE ABOVE OR BELOW THIS LINE             -----

**Comment by kvangent** [comment]
This isn't a bug, the <team_id> was switched to either <old_team_id> or <new_team_id> for clarity. 

You can find the list of current DTS [here](https://github.com/RocketMap/PokeAlarm/wiki/Dynamic-Text-Substitution#gym-text).
