### ISSUE TITLE
[ENHANCEMENT] Twilio Wiki update

### ISSUE THREAD

**Issue by boby361** [RocketMap/PokeAlarm#435]
## Enhancement Description
Update the Twilio Wiki to show an example of the used phone number format in a professional manner.
EX. "+1 111-111-1111"
not   "1111111111"

## Use cases
The service doesn't seem adaptive and this would save some people some time guessing.

**Comment by kvangent** [comment]
I'm not quite sure what this is asking for. As this is a wiki issue, you should submit it to the [wiki github](https://github.com/RocketMap/PokeAlarmWiki).
