### ISSUE TITLE
[BUG] PA freezes after a few minutes of uptime

### ISSUE THREAD

**Issue by JerryLosey** [RocketMap/PokeAlarm#436]
---
## Problem Description
After several minutes of running PA, it freezes. This causes issues with RocketMap sending data to the webhook address as RM displays an error saying:
```2017-09-30 13:45:40,650 [         Thread-42][       webhook][   ERROR] Something's wrong with your webhook: HTTPConnectionPool(host='127.0.0.1', port=4002): Read timed out. (read timeout=1.0).
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_futures/sessions.py", line 73, in wrap
    resp = sup(*args_, **kwargs_)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
```

## Your Environment
Centos 7
Python 2.7.5

RocketMap startup command 
```screen -dmS city1 python runserver.py -ns -hk KEY_HIDDEN -H 0.0.0.0 -P 5001 -ac workers/ZZ/city1 .csv --high-lvl-accounts workers/ZZ/city1 .csv -l '33.22222, 82.33333' -sn city1 -st 1500 -w 250 -gf geofences/ZZ/city1 .txt -enc --enc-whitelist enc-whitelist.txt --hlvl-kph 22 -speed --log-path ~/logs/ --db-threads 50 -pxf ~/ProxyChecker/proxies_good.txt -cf config/new.ini -ed 5 -gi --webhook-blacklist-file blacklist.txt```
PokeAlarm startup command ` python start_pokealarm.py`

Did the issue persist after restarting the script: yes

## Console Output
```
	There is no relevant output in PokeAlarm. As soon as PA freezes, RocketMap shows this:
2017-09-30 14:06:26,155 [         Thread-49][connectionpool][ WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=4000): Read timed out. (read timeout=1.0)",)': /

```

## Your Alarms Config
```#port:
manager_count: 2
key: GMAP_KEY
filters: [filters/standard.json,filters/premium.json]
alarms: [alarms/standard/ZZ/city1 .json,alarms/premium/ZZ/city1 .json]
geofence: [/opt/RocketMap/geofences/ZZ/city1.txt,/opt/RocketMap/geofences/ZZ/city1.txt]
timezone: America/New_York
```

## Troubleshooting Checklist
[X] Most recent version of RocketMap
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by captbunzo** [comment]
I am seeing the same problem with my PokeAlarm instances.

I have four running on the same server receiving input from about 30 hives (with step limits of 25, 50 wph). I've been running these for about a month fine. Just yesterday it started periodically hanging for me.

I have noticed as well that the different instances seem to hang within a short time of each other. This seems to always be within a minute and I've seen it happen within seconds.

I have also noticed that I am getting periodic errors from PokeAlarm that Discord is rejecting alerts with a 401 error. The same Discord hook will also work at other times. I am not sure if this is related, but I thought it might be involved.

**Comment by kvangent** [comment]
There was some discussion in the PA discord - this seems to be related to Discord's notorious unreliability and the connection timeout not being set correctly in the discord alarm. 

A potential fix would be to change line with `timeout=(None, 5)` to `time=5`. If anyone has this problem, please feel free to try it out and report back your findings.

**Comment by JerryLosey** [comment]
@kvangent 
` resp = requests.post(url, json=payload, timeout=(None,5)`
to 
` resp = requests.post(url, json=payload, time=5)`
?
is "time" a typo of "timeout"?

**Comment by kvangent** [comment]
Yeah, that is my mistake. It should be `timeout=5`
