### ISSUE TITLE
[BUG] Typo in Manager.py

### ISSUE THREAD

**Issue by tomballgithub** [RocketMap/PokeAlarm#444]
## Problem Description
If there is an error in get_driving_data, the code gives a 'Unable to get **biking** data.' error message.

`    def get_driving_data(self, lat, lng):
        data = {'drive_dist': "unknown", 'drive_time': "unknown"}
        if self.__latlng is None:
            log.error("No location has been set. Unable to get biking data.")
            return data
 `

## Your Environment
!--- Please post as many details  --
N/A

## Console Output
N/A

## Your Alarms Config
N/A

## Troubleshooting Checklist
N/A

## Enhancement Description
Fix the typo

## Use cases
Error message needs to be correct (driving error not biking error)

## Other Links
N/A

**Comment by kvangent** [comment]
This is already correct in commit 77aa19cead060622f86b87a1db6ba120b5cce6e8 in the dev branch.

**Comment by kvangent** [comment]
Pulled into master in Patch v3.3 (d779668a9b63e1326d8b187f3ac806d538472fb3).
