### ISSUE TITLE
Allow use of multiple google maps keys in config.

### ISSUE THREAD

**Issue by Goldclownfish** [RocketMap/PokeAlarm#446]
[ENHANCEMENT] ---
Allow the use of multiple google maps keys in the config.ini file.

!--- [BUG] 
Without the ability to use multiple gmap keys the wiki is totally incorrect about the ability to run multiple managers inside one instance as after 2500 calls to the google api it will be over used. One single mon that is being encountered can cause this.
## Problem Description
Google maps key gets overused An causes pokealarm to not reports webhook data to discord. Because of failure to get geolocation data.

## Your Environment
!--- Please post as many details  --
Operating System  win 10
Python Version (use `python -V`)  2.7
RocketMap startup command `cmd`  N/a
PokeAlarm startup command `cmd` One pokealarm instance 8 alarms.json files with 8 separate filters.json files

Did the issue persist after restarting the script  
Yes it totally overuses A gmap key in 2 hours or less can easily replicate over an over.

## Console Output
!--- Please post any relevant output provided from the PokeAlarm when you ran it --
```
	
```

## Your 
8 alarms with 8 filters one pa instance
!--- Remove all person data such as API_KEYs or CHAT_IDs --
```json
    CONFIG HERE
N/a

## Troubleshooting Checklist
[ x] Most recent version of RocketMap 
[ x] Most recent version of PokeAlarm
[x ] Checked the Wiki page for service in

**Comment by kvangent** [comment]
I'm not quite sure what you are asking for. You can already assign each manager a different gmaps key. If you are running a big enough set up that you are using your entire quota in less than 2 hours per manager, I suggest you sign up for a premium key. Google is kind enough to provide a free quota for small projects and developers to use- I don't think it's proper that we encourage abuse of that.
