### ISSUE TITLE
[ENHANCEMENT] Add hyperlink to the discord mini-map itself and not just the title text

### ISSUE THREAD

**Issue by wfcook** [RocketMap/PokeAlarm#455]
## Troubleshooting Checklist
- [x ] My RocketMap install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the

## Problem Description
Every new user who views the discord output from my PokeAlarm setup tries to click through to google maps by clicking the mini-map, and they get frustrated that they only get the small GIF. They always have to have it explained to them that they need to click the blue title text. Even seasoned users often click the map when they know better. 

## Environment
Operating System: `WINDOWS10`  
Python Version: 2.7.12 
PokeAlarm Branch: master  
PokeAlarm Version: I'm not at the computer right now will have to check

## PokeAlarm Setup:
Your config file:   
Your filters file:   
Your alarms file:    

## Description
It would be nice if clicking on the mini-map went to the same link as clicking on the title text, or if there was some other way to specify that it needed to.

## Why is this enhancement necessary or useful?
It's *probably* a relatively simple fix and would make the behavior more intuitive

**Comment by kvangent** [comment]
This is something Discord does, to my knowledge there is no setting to override it.

**Comment by wfcook** [comment]
Thanks, I should have guessed that, given the weird formatting it gives the image on some phones (stretching it to screen width).
