### ISSUE TITLE
[BUG] Error in wiki docs for Dynamic Text Substitution

### ISSUE THREAD

**Issue by wfcook** [RocketMap/PokeAlarm#458]
## Problem Description
There is an error in the wiki for dynamic text substitution with gym notifications. The proper tag for gym name is "<gym_name>, but it is currently listed as "<name>"

## Environment
All

## PokeAlarm Setup:
All

## Description
There is an error in the wiki for dynamic text substitution with gym notifications. The proper tag for gym name is "<gym_name>, but it is currently listed as "<name>"

## Why is this enhancement necessary or useful?
Currently, following the wiki results in all gyms being named "unknown" in gym event alerts

## How can this enhancement be accomplished?
Alter the wiki page for Dynamic Text Substitution

**Comment by kvangent** [comment]
Opened issues on Wiki Repo https://github.com/RocketMap/PokeAlarmWiki/issues/58
